### ISSUE TITLE
No module named 'telegram'

### ISSUE THREAD

**Issue by bingbong553** [xdavidhu/lanGhost#7]
I have installed everything correctly but every time I type in Telegram API key I get a;

[I] Loading...

Traceback (most recent call last):
  File "./setup.py", line 83, in <module>
    from telegram.ext import Updater, MessageHandler, Filters
ImportError: No module named 'telegram'
root@DietPi:~/lanGhost#

Could you help me out here old chap?

**Comment by xdavidhu** [comment]
Hey!

`setup.py` should install the Telegram package if you didn't cancel the requirements install and then restart itself and start the Telegram verification process.

Try restarting the `setup.py` script after you made sure it installed the `python-telegram-bot` package.

**Comment by nmkmms** [comment]
Where the python-telegram-bot must be installed?

**Comment by xdavidhu** [comment]
Yes @nmkmms, the `python-telegram-bot` package is necessary for lanGhost to work.

**Comment by tehmaNoF** [comment]
How to install python-telegram-bot ?

**Comment by extbodyan** [comment]
@tehmaNoF git clone https://github.com/python-telegram-bot/python-telegram-bot

**Comment by tehmaNoF** [comment]
Hey, 
Still says : 
File "/root/lanGhost/setup.py", line 83, in <module>
    from telegram.ext import Updater, MessageHandler, Filters
ModuleNotFoundError: No module named 'telegram'

**Comment by xdavidhu** [comment]
@tehmaNoF Try installing it with `pip3`:

`pip3 install python-telegram-bot`

If that's not working:

`python3 -m pip install python-telegram-bot`

If you don't have `pip3`, you can install it with this command:

`sudo apt update && sudo apt install python3-pip`

**Comment by ChandraOrbit** [comment]
I experienced the same thing.
I tried using Raspberry Pi Zero W
